.lavapipe-test:
  stage: software-renderer
  extends:
    - .test-vk
    - .lavapipe-rules
    - .deqp-test-vk
  variables:
    GPU_VERSION: lvp
    VK_DRIVER: lvp
    DEQP_EXPECTED_RENDERER: llvmpipe
    LVP_POISON_MEMORY: "1"

lavapipe:
  tags:
    - mesa-swrast
  variables:
    DEQP_SUITE: lvp
    MESA_VK_IGNORE_CONFORMANCE_WARNING: 1
  stage: software-renderer
  extends:
    - .lavapipe-test

lavapipe-vk-asan:
  extends:
    - .lavapipe-test
  variables:
    GPU_VERSION: lvp-asan
    DEQP_FRACTION: 1000
    # Skip dlclose so that we get good backtraces of the leaks.
    # Don't batch the tests into caselists while we're leaky.
    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.6:libdlclose-skip.so --tests-per-group 1"
  needs:
    - debian/x86_test-vk
    - debian-testing-asan
