# Manual test rules for using anholt's shared g41.
.anholt-g41-test:
  extends:
    - .crocus-rules
    - .test-gl
    - .test-manual-mr
  tags:
    - anholt-g41
  variables:
    GPU_VERSION: crocus-g41
    FLAKES_CHANNEL: "#intel-ci"

# Manual test rules for using anholt's shared hsw.
.anholt-hsw-test:
  extends:
    - .crocus-rules
    - .test-gl
    - .test-manual-mr
  tags:
    - anholt-hsw
  variables:
    GPU_VERSION: crocus-hsw
    FDO_CI_CONCURRENT: 12

crocus-g41:
  extends:
    - .anholt-g41-test
    - .deqp-test
  variables:
    DEQP_SUITE: crocus-g41

crocus-hsw:
  extends:
    - .anholt-hsw-test
    - .deqp-test
  variables:
    DEQP_SUITE: crocus-hsw

crocus-g41-traces:
  extends:
    - .anholt-g41-test
    - .piglit-traces-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-crocus.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "crocus-g41"

crocus-hsw-traces:
  extends:
    - .anholt-hsw-test
    - .piglit-traces-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-crocus.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "crocus-hsw"
