.softpipe-test:
  variables:
    GPU_VERSION: softpipe
    LIBGL_ALWAYS_SOFTWARE: "true"
    FLAKES_CHANNEL: "#mesa-swrast-ci"
    GALLIUM_DRIVER: "softpipe"

.softpipe-deqp-test:
  extends:
    - .test-gl
    - .deqp-test
    - .softpipe-test
    # this must be last to avoid breaking dependency rules
    - .softpipe-rules
  variables:
    DEQP_EXPECTED_RENDERER: softpipe

softpipe:
  tags:
    - mesa-swrast
  variables:
    DEQP_SUITE: softpipe
  extends: .softpipe-deqp-test
  script:
    - LD_LIBRARY_PATH=`pwd`/install/lib xvfb-run --server-args='-noreset' install/deqp-runner.sh

softpipe-asan-gles31:
  variables:
    GPU_VERSION: softpipe-asan
    DEQP_FRACTION: 10
    DEQP_VER: gles31
    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.6"
  extends: .softpipe-deqp-test
  needs:
    - debian/x86_test-gl
    - debian-testing-asan
